services:
  db:
    image: postgres:15-alpine
    container_name: lucas-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pass
    secrets:
      - db_pass
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lucas-network
    volumes:
      - lucas-db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: lucas-api
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Repassando as variáveis do .env para o container Java
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PORT: ${DB_PORT}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      MAIL_USERNAME: ${MAIL_USERNAME}
      FRONTEND_URL: ${FRONTEND_URL}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-default}
      INITIAL_ADMIN_EMAIL: ${INITIAL_ADMIN_EMAIL}
      INITIAL_ADMIN_NAME: ${INITIAL_ADMIN_NAME}
      INITIAL_ADMIN_PASSWORD: ${INITIAL_ADMIN_PASSWORD}
    secrets:
      - db_pass
      - jwt_secret
      - mail_password
      - initial_admin_password
      - encryption_key
      - encryption_key_old
      - cpf_hash_pepper
    ports:
      - "8081:8081"
    networks:
      - lucas-network
    dns:
      - 8.8.8.8
      - 1.1.1.1

  frontend:
    build: ./frontend
    container_name: lucas-web
    restart: always
    environment:
      - API_URL=${API_URL} # Pega do .env (ex: https://lucas.institutomelvin.org/api)
    ports:
      - "8082:80"
    networks:
      - lucas-network

networks:
  lucas-network:
    driver: bridge

volumes:
  lucas-db-data:

secrets:
  db_pass:
    file: ./secrets/db_pass.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt
  mail_password:
    file: ./secrets/mail_password.txt
  initial_admin_password:
    file: ./secrets/initial_admin_password.txt
  encryption_key:
    file: ./secrets/encryption_key.txt
  encryption_key_old:
    file: ./secrets/encryption_key_old.txt
  cpf_hash_pepper:
    file: ./secrets/cpf_hash_pepper.txt
