-- backend/src/main/resources/db/migration/V22__add_unique_constraint_prontuario_appointment.sql
-- E5 (Prontuário Eletrônico) — trava no banco contra prontuário duplicado pra mesma consulta
-- (duplo clique/retry em "Salvar e finalizar atendimento"). A checagem em
-- ProntuarioService.create() (existsByAppointmentId) já existe na aplicação; isso fecha a
-- corrida (check-then-act) no nível do banco também.
--
-- Reaplicação de V20 (desativada em 27/08/2026 — ver
-- memoria-tecnica/decisoes/uk-prontuario-appointment-nao-aplicada-dado-legado.md). Motivo da
-- renumeração em vez de reativar o arquivo V20 original: evitar reescrever um número de versão
-- que já foi tentado (e falhou) em produção — mais seguro nomear como uma migration nova.
--
-- Levantamento completo do dado legado duplicado (feito só na 2ª tentativa — a 1ª só reagiu ao
-- primeiro erro do Flyway, achou só appointment_id=9): 3 pares no total —
-- appointment_id 9, 16 e 50. Todos com conteúdo confirmado idêntico pelo usuário (via UI,
-- comparação visual das notas descriptografadas no histórico do paciente) antes de apagar o
-- registro mais recente de cada par (mantendo o mais antigo como o válido).
ALTER TABLE prontuarios ADD CONSTRAINT uk_prontuario_appointment UNIQUE (appointment_id);
